# Generated by Django 3.2.8 on 2021-10-12 15:03

import database.models.specification
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='下地')),
            ],
            options={
                'verbose_name': '下地',
                'verbose_name_plural': '下地一覧',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(help_text='防水材料のカテゴリ', max_length=255, unique=True, verbose_name='カテゴリ')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='説明文')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ一覧',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='仕様名')),
                ('method_name', models.CharField(blank=True, max_length=255, verbose_name='工法名')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明文')),
                ('part', models.IntegerField(choices=[('平場', '平場'), ('立上り', '立上り')], verbose_name='適用部位')),
                ('how_to_paste', models.IntegerField(choices=[(0, '密着'), (1, '絶縁')], verbose_name='密着/絶縁')),
                ('walk', models.IntegerField(choices=[(0, '非歩行'), (1, '軽歩行'), (2, '歩行')], verbose_name='歩行用途')),
                ('insulation', models.IntegerField(choices=[(0, '非断熱'), (1, '断熱')], verbose_name='非断熱/断熱')),
                ('is_display', models.BooleanField(default=True, help_text='公開／非公開', verbose_name='表示')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('image1', models.ImageField(blank=True, upload_to=database.models.specification.specification_directory_path)),
                ('image2', models.ImageField(blank=True, upload_to=database.models.specification.specification_directory_path)),
                ('image3', models.ImageField(blank=True, upload_to=database.models.specification.specification_directory_path)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('base', models.ManyToManyField(to='database.Base', verbose_name='適用下地')),
            ],
            options={
                'verbose_name': '仕様',
                'verbose_name_plural': '仕様一覧',
            },
        ),
    ]
