# Generated by Django 3.2.8 on 2021-11-15 10:50

import database.models.document
import database.models.material
import database.models.specification
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='下地')),
            ],
            options={
                'verbose_name': '下地',
                'verbose_name_plural': '下地一覧',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('normalize_name', models.CharField(blank=True, help_text='例：アスファルト系プライマー', max_length=255, verbose_name='一般名称')),
                ('standard', models.TextField(help_text='例：1m × 8m', max_length=255, verbose_name='規格')),
                ('remarks', models.TextField(blank=True, max_length=255, verbose_name='備考')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='説明文')),
                ('bto', models.BooleanField(default=False, verbose_name='受注生産品')),
                ('material_image', models.ImageField(blank=True, upload_to=database.models.material.material_image_path, verbose_name='イメージ')),
                ('label_image', models.ImageField(blank=True, upload_to=database.models.material.material_label_image_path, verbose_name='ラベル')),
                ('packing_image', models.ImageField(blank=True, upload_to=database.models.material.material_packing_image_path, verbose_name='荷姿')),
                ('cad', models.FileField(blank=True, upload_to=database.models.material.material_cad_path, verbose_name='CAD')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(help_text='例：シート類、プライマー', max_length=50, unique=True, verbose_name='材料種別')),
                ('order', models.IntegerField(verbose_name='並び順')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='MaterialDocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='商品書類カテゴリ名')),
            ],
            options={
                'verbose_name': '商品書類カテゴリ',
                'verbose_name_plural': '商品書類カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工法名')),
                ('normalize_name', models.CharField(max_length=100, verbose_name='一般名称')),
                ('release_date', models.DateField(verbose_name='発売日')),
            ],
            options={
                'verbose_name': '工法',
                'verbose_name_plural': '工法',
            },
        ),
        migrations.CreateModel(
            name='MethodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('image', models.ImageField(blank=True, upload_to=database.models.specification.method_category_image_path, verbose_name='イメージ図')),
            ],
            options={
                'verbose_name': '工法カテゴリ',
                'verbose_name_plural': '工法カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='部位')),
            ],
            options={
                'verbose_name': '部位',
                'verbose_name_plural': '部位一覧',
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='貼り方')),
            ],
            options={
                'verbose_name': '貼り方',
                'verbose_name_plural': '貼り方',
            },
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('length', models.CharField(max_length=20, verbose_name='勾配')),
            ],
            options={
                'verbose_name': '勾配',
                'verbose_name_plural': '勾配',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='仕様名')),
                ('method_name', models.CharField(blank=True, max_length=255, verbose_name='工法名')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明文')),
                ('is_insulation', models.BooleanField(default=False, help_text='非断熱／断熱', verbose_name='断熱')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='重量(kg/㎡)')),
                ('thickness', models.IntegerField(blank=True, null=True, verbose_name='厚み/mm')),
                ('co2_usage', models.FloatField(blank=True, null=True, verbose_name='CO2使用量(kg/㎡)')),
                ('service_life', models.IntegerField(blank=True, null=True, verbose_name='耐用年数/年')),
                ('is_display', models.BooleanField(default=True, help_text='公開／非公開', verbose_name='公開')),
                ('remarks', models.TextField(blank=True, verbose_name='備考')),
                ('image', models.ImageField(blank=True, upload_to=database.models.specification.specification_image_path, verbose_name='イメージ図')),
                ('interface', models.FileField(blank=True, upload_to=database.models.specification.specification_interface_path, verbose_name='納まり図')),
                ('cad', models.FileField(blank=True, upload_to=database.models.specification.specification_cad_path, verbose_name='CAD図')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('base', models.ManyToManyField(to='database.Base', verbose_name='適用下地')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.method', verbose_name='工法')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.part', verbose_name='部位')),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.paste', verbose_name='貼り方')),
                ('slope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.slope', verbose_name='勾配')),
            ],
            options={
                'verbose_name': '仕様',
                'verbose_name_plural': '仕様一覧',
            },
        ),
        migrations.CreateModel(
            name='SpecificationDocumentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仕様書類カテゴリ名')),
            ],
            options={
                'verbose_name': '仕様書類カテゴリ',
                'verbose_name_plural': '仕様書類カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='歩行用途')),
            ],
            options={
                'verbose_name': '歩行用途',
                'verbose_name_plural': '歩行用途',
            },
        ),
        migrations.CreateModel(
            name='SpecificationProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='行程は1-20の間です', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='行程')),
                ('unit', models.IntegerField(blank=True, choices=[(0, '個'), (1, 'kg/㎡')], null=True, verbose_name='単位')),
                ('min_quantity', models.FloatField(blank=True, help_text='数量に幅が無い場合には最小数量を記入します', null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(1000.0)], verbose_name='最小数量')),
                ('max_quantity', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(1000.0)], verbose_name='最大数量')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='備考')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process', to='database.material', verbose_name='材料')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process', to='database.specification', verbose_name='仕様')),
            ],
            options={
                'verbose_name': '仕様工程',
                'verbose_name_plural': '仕様工程',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SpecificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(upload_to=database.models.document.specification_document_path, verbose_name='ファイル')),
                ('is_display', models.BooleanField(default=True, help_text='公開／非公開', verbose_name='公開')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.specificationdocumentcategory', verbose_name='カテゴリ')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='database.specification', verbose_name='仕様')),
            ],
            options={
                'verbose_name': '仕様書類',
                'verbose_name_plural': '仕様書類',
            },
        ),
        migrations.CreateModel(
            name='SpecificationCompose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='使用頻度など', verbose_name='表示順序')),
                ('main_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compose', to='database.specification', verbose_name='メイン仕様')),
                ('sub_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_compose', to='database.specification', verbose_name='サブ仕様')),
            ],
            options={
                'verbose_name': '仕様構成',
                'verbose_name_plural': '仕様構成',
            },
        ),
        migrations.AddField(
            model_name='specification',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.walk', verbose_name='歩行用途'),
        ),
        migrations.AddField(
            model_name='method',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.methodcategory', verbose_name='カテゴリ'),
        ),
        migrations.CreateModel(
            name='MaterialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('file', models.FileField(upload_to=database.models.document.material_document_path, verbose_name='ファイル')),
                ('is_display', models.BooleanField(default=True, help_text='公開／非公開', verbose_name='公開')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.materialdocumentcategory', verbose_name='カテゴリ')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document', to='database.material', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品書類',
                'verbose_name_plural': '商品書類',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.materialcategory', verbose_name='カテゴリ'),
        ),
    ]
