# Generated by Django 3.2.8 on 2021-10-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='co2_usage',
            field=models.FloatField(blank=True, default=1, verbose_name='CO2使用量(kg/㎡)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='service_life',
            field=models.IntegerField(blank=True, default=1, verbose_name='耐用年数/年'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='thickness',
            field=models.IntegerField(blank=True, default=1, verbose_name='厚み/mm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specification',
            name='weight',
            field=models.FloatField(blank=True, default=1, verbose_name='重量(kg/㎡)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specification',
            name='is_insulation',
            field=models.BooleanField(default=False, help_text='非断熱／断熱', verbose_name='断熱'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.part', verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='paste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.paste', verbose_name='貼り方'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='slope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.slope', verbose_name='勾配'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='walk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.walk', verbose_name='歩行用途'),
        ),
    ]
