# Generated by Django 3.2.8 on 2021-11-15 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationcompose',
            name='order',
            field=models.IntegerField(help_text='使用頻度など', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='表示順序'),
        ),
    ]
