# Generated by Django 3.2.8 on 2021-10-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211014_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='co2_usage',
            field=models.FloatField(blank=True, null=True, verbose_name='CO2使用量(kg/㎡)'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='service_life',
            field=models.IntegerField(blank=True, null=True, verbose_name='耐用年数/年'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='thickness',
            field=models.IntegerField(blank=True, null=True, verbose_name='厚み/mm'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='重量(kg/㎡)'),
        ),
    ]
