# Generated by Django 3.2.8 on 2021-10-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_specificationdocument_specificationdocumentcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationdocument',
            options={'verbose_name': '仕様書類', 'verbose_name_plural': '仕様書類'},
        ),
        migrations.AddField(
            model_name='specificationdocument',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='database.specificationdocumentcategory', verbose_name='カテゴリ'),
            preserve_default=False,
        ),
    ]
