# Generated by Django 3.2.8 on 2021-10-13 16:35

import database.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20211014_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationdocument',
            name='file',
            field=models.FileField(upload_to=database.models.document.specification_document_path, verbose_name='ファイル'),
        ),
    ]
