# Generated by Django 3.2.8 on 2021-10-13 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_specificationdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationdocument',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificationdocument',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
