# Generated by Django 3.2.8 on 2021-10-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20211015_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificationdocument',
            name='name',
        ),
    ]
