# Generated by Django 3.2.8 on 2021-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_remove_specificationdocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationdocument',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
