# Generated by Django 3.2.8 on 2021-10-15 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_materialdocument_materialdocumentcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationCompose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='使用頻度など', verbose_name='表示順序')),
                ('main_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compose', to='database.specification', verbose_name='メイン仕様')),
                ('sub_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_compose', to='database.specification', verbose_name='サブ仕様')),
            ],
            options={
                'verbose_name': '仕様構成',
                'verbose_name_plural': '仕様構成',
            },
        ),
    ]
