# Generated by Django 3.2.8 on 2021-10-23 13:29

import database.models.specification
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20211017_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明文'),
        ),
        migrations.AddField(
            model_name='methodcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=database.models.specification.method_category_image_path, verbose_name='イメージ図'),
        ),
    ]
